// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ruoudkyjtzjrzhfaovyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1b3Vka3lqdHpqcnpoZmFvdnlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3OTUxMDgsImV4cCI6MjA1NzM3MTEwOH0.0qNphtYdO6-kd3vkuMtu1Vn15WQT0BXorjrMZCsb7Zk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);